name: Azure Deployment

on:
  push:
    branches:
      - main
    paths:
        - 'infra/**'
  workflow_dispatch:

env:
  RG_NAME: 'rg-ai-demo'
  LOCATION: 'canadacentral'

jobs:
    create-resources:
        runs-on: ubuntu-latest

        steps:

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Azure CLI
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
            
            - name: create-resources
              run: |
                az deployment sub create --location canadacentral --template-file ./infra/main.bicep --parameters ocation=${{ env.LOCATION}} rgName=${{ env.RG_NAME}}
