name: Create Azure Resources

on:
  workflow_dispatch:

env:
  RG_NAME: ${{secrets.RG_NAME}}
  LOCATION: 'eastus'
  DEPLOYMENT_NAME: 'ai-demo-deployment'

jobs:
  create-resources:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
            
      - name: Deploy Azure Resources
        id: createResources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          scope: subscription
          region: ${{ env.LOCATION }}
          template: ./infra/main.bicep
          parameters: location=${{ env.LOCATION}} rgName=${{ env.RG_NAME}}
          
      - uses: gliech/create-github-secret-action@v1
        name: Write function app name
        with:
          name: FUNCTIONAPP_NAME
          value: ${{ steps.createResources.outputs.functionName }}
          pa_token: ${{ secrets.PA_TOKEN }}          
