name: Train document intelligent model

on:
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest    
    env:
        FORM_RECOGNIZER_ENDPOINT: ${{ secrets.FORM_RECOGNIZER_ENDPOINT }}
        FORM_RECOGNIZER_API_KEY: ${{ secrets.FORM_RECOGNIZER_API_KEY }}
        STORAGECNXSTRING: ${{ secrets.STORAGE_CNX_STRING }}
        CONTAINERNAME: 'trainingassets'
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
  
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      
      - name: Build utility helper
        run: dotnet build  ./modelUtility.csproj --configuration Release --output ../artefact
        working-directory: ./src/Utility/modelUtility
